config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  
  get 'sign_up' => 'registrations#new'

  post 'sign_up' => 'registrations#create'
  get 'confirm' => 'registrations#confirm'
  get 'welcome' => 'registrations#welcome'

  resources :group_messages

  resources :channel_accesses do
    collection do
      post 'national_gateway'
    end
  end

  resources :channels do
    member do
      put 'state'
    end
  end

  resources :passwords, only: [:new, :update] do
    collection do
      put 'request_change'
      put 'reset'
      get 'change'
    end
  end

  delete 'sign_out' => 'sessions#destroy'

  resources :permissions
  resources :project_permissions
  resources :channel_permissions

  resources :projects do
    member do
      get 'share'
      get 'sms_setting'
      post 'update_sms_setting'
    end

    collection do
      get 'list'
    end

    resources :alerts do

      collection do
        get 'matched'
        get 'share'
      end

      member do
        get 'new_groups'
        get 'new_keywords'
      end
      
    end
  end

  resources :alerts, only: [] do
    collection do
      get 'matched'
    end

    member do
      get 'new_groups'
      get 'new_keywords'
    end

    resources :alert_groups
    resources :alert_keywords

    resources :feed_entries do
      collection do
        get 'matched'
      end
    end
  end

  resources :groups do
    member do
      get 'new_members'
      get 'alerts'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
      get 'alerts'
    end
  end

  resources :users, only: [] do
    collection do
      get 'profile'
      put 'update_profile'

      get 'password'
      put 'update_password'
      get 'list'
    end

    member do
      put 'reset'
    end
  end

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Group < ActiveRecord::Base
  belongs_to :user

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships

  has_many :alert_groups, dependent: :destroy
  has_many :alerts, through: :alert_groups

  has_many :group_permissions
  has_many :users, through: :group_permissions, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

  def self.excludes(groups)
    where([" id not in (?)", groups])
  end

  def self.from_query(query)
    like = "#{query}%"
    where([ "name LIKE ? OR description LIKE ? ", like, like ])
  end

  def self.unique_members(groups)
    Member.joins(:memberships).where([" memberships.group_id  in (?)", groups]).uniq
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups
                          .includes(:memberships, :members)
                          .order('groups.name')
                          .page(params[:page])

    @group_permissions = current_user.high_level_group_permissions
                                     .includes(:alert, :project, group: [:memberships, :members])
                                     .page(params[:shared_page])
  end

  def new_members

    existing_members = group_with_role.object.members.ids

    members = current_user.members
    members = members.excludes(existing_members) if existing_members.count > 0
    members = members.from_query(params[:q]) if params[:q].present?
    render json: members
  end

  def new
    group = current_user.groups.build
    @group_with_role = ObjectWithRole.new(group)
  end

  def create
    group = current_user.groups.build(filter_params)
    @group_with_role = ObjectWithRole.new(group)
  
    if @group_with_role.save
      redirect_to edit_group_path(@group_with_role.object), notice: 'Group has been created'
    else
      flash.now[:alert] = 'Failed to create group'
      render :new
    end
  end

  def edit
    group_with_role
  end

  def update
    group_with_role.has_admin_role!
    if(group_with_role.update_attributes(filter_params))
      redirect_to groups_path, notice: 'Group has been updated'
    else
      flash.now[:alert] = 'Failed to update'
      render :edit
    end
  end

  def destroy
    group_with_role.has_admin_role!
    if(group_with_role.destroy)
      redirect_to groups_path, notice: 'Group has been deleted'
    else
      redirect_to groups_path, alert: "Failed to delete the group"
    end
  end

  def alerts
    @group = group_with_role.object
    render layout: false
  end

  private
  def group_with_role
    @group_with_role ||= current_user.accessible_group(params[:id])
  end

  def filter_params
    params.require(:group).permit(:name, :description)
  end

end

app/views/groups/_form.html.erb
<%=simple_form_for(group_with_role.object, html: { class: 'form-inline form'}) do |f| %>
  <% disabled = group_with_role.has_admin_role? ? {} : {disabled: 'disabled'} %>
  <div class='input-row'>
    <%=f.input :name, input_html: {class: 'form-control'}.merge(disabled) %>
  </div>

  <div class='input-row'>
    <%=f.input :description, input_html: {class: 'form-control', rows: '6'}.merge(disabled) %>
  </div>

  <% if group_with_role.has_admin_role? %>
    <div class='form-group form-action-group'>
      <label></label>
      <%=f.submit 'Save', label: false, class: 'btn btn-primary btn-app' %>
    </div>
  <% end %>

<% end %>

app/views/groups/_group.html.erb
<tr>
  <td><%= link_to group_with_role.object.name, edit_group_path(group_with_role.object) %></td>
  <td><%= truncate(group_with_role.object.description, length: 45) %></td>

  <td align="center">
    <%= link_to "View", alerts_group_path(group_with_role.object.id), class:'content-url', data: {id: group_with_role.object.id} %>
  </td>

  <td>
     <%= truncate(group_with_role.object.members.map(&:full_name).join(", "), length: 45) %>
  </td>

  <td>
     <% if group_with_role.has_admin_role? %>
       <%= link_edit " ", edit_group_path(group_with_role.object) %>
       <%= link_destroy " ", group_path(group_with_role.object), method: :delete, data: { confirm: 'Are you sure to delete this group ?' } %>
     <% end %>
  </td>
</tr>

app/views/groups/_search_member.html.erb
<div class='search-wrapper'>
  <div class="input-group">
    <input id='member-typeahead' type="text" 
          class="form-control typeahead" placeholder="Add Recipient"
          data-url="<%= new_members_group_path(group_with_role.object) %>"

          >
    <span class="input-group-btn">
      <button id='add-member-group' class="btn btn-primary btn-app" type="button">Add Recipient</button>
    </span>
  </div>

  <input id='member-value' 
         type='hidden'
         value=''
         data-url='<%=memberships_path() %>'
         data-group-id='<%=group_with_role.object.id %>'
         >
</div>

app/views/groups/alerts.html.erb
<h4>
  <b>Group: <%= @group.name %></b>
</h4>

<%= render 'shared/alerts_with_projects', alerts: @group.alerts.includes(:project) %>

app/views/groups/edit.html.erb
<% content_for(:title) { "Edit Group"} %>
<% breadcrumb_buffer([{ "Groups": groups_path},
                      { "#{@group_with_role.object.name}": nil}
  ]) %>

<%= render "shared/group_recipient_tab", group_recipient_tab_index: 1 %>

<div class='form-wrapper'>
  <%= panel "Edit Group" do %> 
    <%= render 'form', group_with_role: @group_with_role %>
  <% end %>

  <br />
  <div class=' header-wrapper clearfix'>
    <div class='pull-left'>
      <h3 class='header-title'> Recipients in this group</h3>
    </div>

    <div class='pull-right'>
      <div class="autocomplete-box"> <%= render('search_member', group_with_role: @group_with_role) if @group_with_role.has_admin_role? %></div>
    </div>
  </div>


  <div id='member-list'>
    <%= render 'memberships/members', group_with_role: @group_with_role %>
  </div>
</div>

app/views/groups/index.html.erb
<% content_for(:title) { "Groups"} %>
<% breadcrumb_buffer([{ "Groups": nil}]) %>

<%= render "shared/group_recipient_tab", group_recipient_tab_index: 1 %>

<div class=' header-wrapper clearfix'>
  <div class='pull-left'>
    <h3 class='header-title'> My Groups </h3>
  </div>

  <div class='pull-right'>
    <%= link_new 'New Group', new_group_path() %>
  </div>
</div>

<div class="panel panel-info">
  <table class='table table-responsive'>
    <thead>
      <tr>
        <td width="150">Name</td>
        <td>Description</td>
        <td align="center" >Projects/Alerts</td>
        <td>Recipients</td>
        <td class='td-last'>Action</td>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
        <%= render 'group', group_with_role: ObjectWithRole.new(group) %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate_for(@groups) %>


<% if @group_permissions.length > 0 %>
  <br />
  <br />
  <br />

  <h3 class='header-title'> Shared Groups</h3>

  <div class="panel panel-info">
    <table class='table table-responsive'>
      <thead>
        <tr>
          <td width="150">Name</td>
          <td>Description</td>
          <td align="center">Projects/Alerts</td>
          <td>Recipients</td>
          <td class='td-last'>Action</td>
        </tr>
      </thead>

      <tbody>
        <% @group_permissions.each do |group_permission| %>
          <%= render 'group', group_with_role: ObjectWithRole.new(group_permission.group, group_permission.role) %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate_for(@group_permissions, param_name: :shared_page) %>
<% end %>

<%= render 'shared/content_url_modal' %>

app/views/groups/new.html.erb
<% content_for(:title) { "New Group"} %>
<% breadcrumb_buffer([{ "Groups": groups_path},
                      { "New Group": nil}
  ]) %>

<%= render "shared/group_recipient_tab", group_recipient_tab_index: 1 %>

<%= panel "New Group" do %>
  <%= render 'form', group_with_role: @group_with_role %>
<% end %>