config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  
  get 'sign_up' => 'registrations#new'

  post 'sign_up' => 'registrations#create'
  get 'confirm' => 'registrations#confirm'
  get 'welcome' => 'registrations#welcome'

  resources :group_messages

  resources :channel_accesses do
    collection do
      post 'national_gateway'
    end
  end

  resources :channels do
    member do
      put 'state'
    end
  end

  resources :passwords, only: [:new, :update] do
    collection do
      put 'request_change'
      put 'reset'
      get 'change'
    end
  end

  delete 'sign_out' => 'sessions#destroy'

  resources :permissions
  resources :project_permissions
  resources :channel_permissions

  resources :projects do
    member do
      get 'share'
      get 'sms_setting'
      post 'update_sms_setting'
    end

    collection do
      get 'list'
    end

    resources :alerts do

      collection do
        get 'matched'
        get 'share'
      end

      member do
        get 'new_groups'
        get 'new_keywords'
      end
      
    end
  end

  resources :alerts, only: [] do
    collection do
      get 'matched'
    end

    member do
      get 'new_groups'
      get 'new_keywords'
    end

    resources :alert_groups
    resources :alert_keywords

    resources :feed_entries do
      collection do
        get 'matched'
      end
    end
  end

  resources :groups do
    member do
      get 'new_members'
      get 'alerts'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
      get 'alerts'
    end
  end

  resources :users, only: [] do
    collection do
      get 'profile'
      put 'update_profile'

      get 'password'
      put 'update_password'
      get 'list'
    end

    member do
      put 'reset'
    end
  end

end

app/views/shared/_account.html.erb
Don't have an account <b> <%=link_to 'Sign Up', sign_up_path%> </b> or Could not login <b><%=link_to 'Forget Password', new_password_path%></b>

app/views/shared/_alerts_with_projects.html.erb
<div class="panel panel-info">
  <table class='table table-responsive'>
    <thead>
      <tr>
        <td> Project </td>
        <td> Alert </td>
      </tr>
    </thead>

    <tbody>
      <% alerts.each do |alert| %>
        <tr>
          <td><%= alert.project.name %></td>
          <td><%= alert.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_content_url_modal.erb
<div class="modal" id="content-url-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">
        Content is loading...
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-app btn-primary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

app/views/shared/_email_delivery.html.erb
<p>
  It might take up to minutes to deliver email to you, If you think there's something wrong with our delivery, please contact us: 
  <%= mail_to ENV['SUPPORT_EMAIL'], ENV['SUPPORT_EMAIL'] %>
</p>

app/views/shared/_group_recipient_tab.html.erb
<ul class="nav nav-tabs">

  <li role="presentation" class="<%= active_tab_for_index(1, group_recipient_tab_index) %>">
    <%= link_to "Groups", groups_path %>
  </li>

  <li role="presentation" class="<%= active_tab_for_index(2, group_recipient_tab_index) %>">
    <%= link_to "Recipients", members_path %>
  </li>

</ul>

app/views/shared/_groups_recipients.html.erb
<%
  if group_recipient_tab == 2
    group_recipient_tab1_state = ''
    group_recipient_tab2_state = 'active'
  else
    group_recipient_tab1_state = 'active'
    group_recipient_tab2_state = ''
  end
%>

<div role="tabpanel">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="<%=group_recipient_tab1_state%>">
      <a href="#groups" aria-controls="overview" role="tab" data-toggle="tab">Groups</a>
    </li>

    <li role="presentation" class="<%=group_recipient_tab2_state%>">
       <a href="#recipients" aria-controls="alerts" role="tab" data-toggle="tab">Recipients</a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane <%=group_recipient_tab1_state%>" id="groups">
      <br />
      <%= render 'shared/groups', groups: groups %>
    </div>

    <div role="tabpanel" class="tab-pane <%=group_recipient_tab2_state%>" id="recipients">
      <br />
      <%= render 'shared/members', members: members %>
    </div>
  </div>
</div>

app/views/shared/_project_alert.html.erb
<ul class="nav nav-tabs">

  <li role="presentation" class="<%= active_tab_for_index(1, project_tab) %>">
    <%= link_to "Overview", url_tab1 %>
  </li>

  <li role="presentation" class="<%= active_tab_for_index(2, project_tab)%> <%= is_enable_alert_and_sms_tab %>">
    <%= link_to "Alerts", url_tab2 %>
  </li>

  <li role="presentation" class="<%= active_tab_for_index(3, project_tab) %> <%= is_enable_alert_and_sms_tab %>">
    <%= link_to "SMS Setting", url_tab3 %>
  </li>

</ul>

app/views/shared/_project_overview.html.erb
<%
  if project_in_tab == 1
    project_in_tab1_state = 'active'
    project_in_tab2_state = ''
  else
    project_in_tab1_state = ''
    project_in_tab2_state = 'active'
  end
%>

<div role="tabpanel">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="<%=project_in_tab1_state %>">
      <a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">Overview</a>
    </li>
    <li role="presentation" class="<%=project_in_tab2_state %>">
      <% if project.persisted? %>
       <a href="#alerts" aria-controls="alerts" role="tab" data-toggle="tab">Alerts</a>
      <% else %>
        <a href="javascript:void(0)" style='cursor: auto;'>Alerts</a>
      <% end %>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane <%=project_in_tab1_state%>" id="overview">
      <%= render 'shared/project_form', project: project %>
      <% if project.persisted? %>
      <p style="margin-top: 60px;">
        <%= link_to project_path(project), method: :delete, style: 'margin-left: 13em;' do %>
          <i class='glyphicon glyphicon-trash'> </i> Delete this project
        <% end %>
      </p>
      <% end %>
    </div>

    <% if project.persisted? %>
      <div role="tabpanel" class="tab-pane <%=project_in_tab2_state%>" id="alerts">
        <%= yield(:alert_tab) %>
      </div>
    <% end %>

  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag url, class: 'search-form', style: 'display:none', method: :get do %>
  <div class='search-box'>
    <i class='glyphicon glyphicon-search'> </i>
    <%= text_field_tag :query, params[:query], placeholder: 'Search' %>
  </div>
<% end %>