config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  
  get 'sign_up' => 'registrations#new'

  post 'sign_up' => 'registrations#create'
  get 'confirm' => 'registrations#confirm'
  get 'welcome' => 'registrations#welcome'

  resources :group_messages

  resources :channel_accesses do
    collection do
      post 'national_gateway'
    end
  end

  resources :channels do
    member do
      put 'state'
    end
  end

  resources :passwords, only: [:new, :update] do
    collection do
      put 'request_change'
      put 'reset'
      get 'change'
    end
  end

  delete 'sign_out' => 'sessions#destroy'

  resources :permissions
  resources :project_permissions
  resources :channel_permissions

  resources :projects do
    member do
      get 'share'
      get 'sms_setting'
      post 'update_sms_setting'
    end

    collection do
      get 'list'
    end

    resources :alerts do

      collection do
        get 'matched'
        get 'share'
      end

      member do
        get 'new_groups'
        get 'new_keywords'
      end
      
    end
  end

  resources :alerts, only: [] do
    collection do
      get 'matched'
    end

    member do
      get 'new_groups'
      get 'new_keywords'
    end

    resources :alert_groups
    resources :alert_keywords

    resources :feed_entries do
      collection do
        get 'matched'
      end
    end
  end

  resources :groups do
    member do
      get 'new_members'
      get 'alerts'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
      get 'alerts'
    end
  end

  resources :users, only: [] do
    collection do
      get 'profile'
      put 'update_profile'

      get 'password'
      put 'update_password'
      get 'list'
    end

    member do
      put 'reset'
    end
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  belongs_to :user

  has_many :project_permissions, dependent: :destroy
  has_many :shared_users, class_name: 'User', through: :project_permissions

  has_many :group_permissions, dependent: :destroy

  validates :name, presence: true

  has_many :alerts, dependent: :destroy
  has_many :channel_accesses, dependent: :destroy
  has_many :channels, through: :channel_accesses

  def access_role=(role)
    @access_role = role
    self
  end

  def admin_access_role?
    @access_role != User::PERMISSION_ROLE_NORMAL
  end

  def accessible_channels
    channel_ids = self.channels.map(&:id) + self.user.my_channels.pluck(:id) + self.user.channel_permissions.pluck(:channel_id)
    Channel.where(id: channel_ids, is_enable: true)
  end

  def accessible_channel(channel_id)
    channels = self.accessible_channels
    channel = channels.where(id: channel_id)
    return ObjectWithRole.new(channel) if channel

    permission = self.user.channel_permissions.find_by(channel_id: channel_id)
    return ObjectWithRole.new(permission.channel, permission.role) if permission
    raise ActiveRecord::RecordNotFound

  end
 
  def is_active_channel? channel
    channel_access = self.channel_accesses.select { |c| c.channel_id ==  channel.id}.first
    channel_access ? channel_access.is_active : false
  end

  def self.from_query(query)
    like = "#{query}%"
    where([ "name LIKE ?", like ]) 
  end

  def self.query_by_user(user_id)
    if user_id == ''
      all
    else
      where(user_id: user_id)
    end
  end

  def self.query_by_user_email(email)
    if email && email != ""
      return self.joins(:user).where('users.email' => email).group('users.email', 'name')
    end
    self.joins(:user).group('users.email', 'name')
  end

  def reset_national_gateway_channel_access channel_ids
    national_gateway_ids = Channel.national_gateway.pluck(:id)
    channel_accesses = self.channel_accesses.where(channel_id: national_gateway_ids)   
    channel_accesses.where.not(channel_id: channel_ids).destroy_all
  end

  def build_national_gateway_channel_access channel_ids
    self.reset_national_gateway_channel_access channel_ids
    if channel_ids
      ChannelAccess.transaction do
        channel_ids.each do |channel_id|
          is_exist_channel_access = self.channel_accesses.find_by_channel_id(channel_id)
          if !is_exist_channel_access
            channel_access = self.channel_accesses.build(channel_id: channel_id)
            channel_access.save
          end
        end
      end
    end
  end  

  def enabled_channels
    self.channels.where('channel_accesses.is_active = ? && channels.is_enable = ?', true, true)
  end

  def is_time_appropiate? sms_time
    if self.sms_alert_started_at && self.sms_alert_ended_at
      working_minutes = sms_time.hour * 60 + sms_time.min
      return in_minutes(self.sms_alert_started_at) <= working_minutes && working_minutes <= in_minutes(self.sms_alert_ended_at)
    end
    return false
  end 

  def in_minutes field
    field.split(":")[0].to_i * 60 + field.split(":")[1].to_i
  end

  def is_accessible_to_national_gateway?
    national_channel_ids = Channel.national_gateway.pluck(:id)
    project_national_channels = self.channels.where(id: national_channel_ids)
    if project_national_channels.length > 0
      true
    else
      false
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @my_projects = current_user.my_projects
                               .page(params[:page])

    @project_permissions = current_user.project_permissions
                                       .includes(:project)
                                       .page(params[:shared_page])
  end

  def new
    @project_with_role = ObjectWithRole.new(current_user.my_projects.build)
  end

  def create
    @project_with_role = ObjectWithRole.new(current_user.my_projects.build(filter_params))
    if @project_with_role.save
      redirect_to edit_project_path(@project_with_role.object), notice: 'Project has been created'
    else
      flash.now[:alert] = "Failed to create project"
      render :new
    end
  end

  def edit
    @project_with_role = current_user.accessible_project(params[:id])
  end

  def share
    @project_with_role = current_user.shared_projects.find(params[:id])
  end

  def update
    @project_with_role = current_user.accessible_project(params[:id])
    @project_with_role.has_admin_role!

    if @project_with_role.update_attributes(filter_params)
      redirect_to projects_path, notice: 'Project updated'
    else
      flash.now[:alert] = "Failed to update project"
      render :edit
    end
  end

  def destroy
    @project_with_role = current_user.accessible_project(params[:id])
    @project_with_role.has_admin_role!

    begin 
      @project_with_role.destroy
      redirect_to projects_path, notice: 'Project has been deleted'
    rescue ActiveRecord::StatementInvalid => ex
      flash.now[:alert] = "To be able to delete please delete all related records first"
      render :edit
    end
  end

  def sms_setting
    @project_with_role = current_user.accessible_project(params[:id])
  end

  def update_sms_setting
    @project_with_role = current_user.accessible_project(params[:id])
    if valid_params?
      @project_with_role.object.update_attributes(filter_params.except("channel_ids"))
      channel_ids = filter_params[:channel_ids]
      channel_accesses = @project_with_role.object.channel_accesses
      #reset channel_accesses
      channel_accesses.update_all(is_active: false)
      channel_ids.each do |c_id|
        channel_access = channel_accesses.select { |c| c.channel_id == c_id.to_i }.first
        if channel_access
          channel_access.update_attributes(is_active: true)
        else
          ChannelAccess.create(project_id: @project_with_role.object.id, channel_id: c_id, is_active: true)
        end
      end
      redirect_to projects_path, notice: 'Project updated'
    else
      redirect_to sms_setting_project_path, :flash => { :alert => "Please enter all required fields." }
    end
  end

  def list
    @projects = Project.query_by_user(params[:user_id])
    @projects = @projects.from_query(params[:project_name])
    render json: @projects
  end

  private

  def filter_params
    params.require(:project).permit(:name, :description, :sms_alert_started_at, :sms_alert_ended_at, :sms_alert_template, channel_ids: [])
  end

  def valid_params?
    filter_params[:channel_ids].present? && filter_params[:sms_alert_started_at].present? && filter_params[:sms_alert_ended_at].present? && filter_params[:sms_alert_template].present?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/_form.html.erb
<%=simple_form_for(project_with_role.object, html: { class: 'form-inline form'}) do |f| %>

  <% input_attrs = project_with_role.has_admin_role? ? {} : {disabled: 'disabled'} %>

  <%=f.input :name, input_html: {class: 'form-control'}.merge(input_attrs) %>
  <%=f.input :description, as: :text, input_html: {class: 'form-control', rows: 4}.merge(input_attrs), 
             wrapper_html: { class: 'inline'} %>
  <% if project_with_role.has_admin_role? %>
    <div class='form-group form-action-group'>
      <label></label>
      <%=f.submit 'Save', label: false, class: 'btn btn-primary btn-app' %>
    </div>
  <% end %>

<% end %>

app/views/projects/_project.html.erb
<tr>
  <td>
    <%=link_to project_with_role.object.name, edit_project_path(project_with_role.object) %>
    <% if show_role %>
      - <span style='color: gray; font-style: italic' > <%= project_with_role.role %></span>
    <% end %>
  </td>

  <td> <%= project_with_role.object.description %> </td>

  <td>
    <% if project_with_role.has_admin_role? %>
      <%= link_edit " ", edit_project_path(project_with_role.object) %>
      <%= link_destroy " ", project_path(project_with_role.object),
                            method: :delete,
                            data: { confirm: 'Are you sure to delete this project ?', 'confirm-explain' => "All alerts under this project will also be deleted." } %>
    <% end %>
  </td>
</tr>

app/views/projects/edit.html.erb
<% content_for(:title) { "Edit Project"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      {"#{@project_with_role.object.name}": nil}]) %>

<%= render 'shared/project_alert',
           project_tab: 1,
           url_tab1: edit_project_url(@project_with_role.object),
           url_tab2: project_alerts_path(@project_with_role.object),
           url_tab3: sms_setting_project_path(@project_with_role.object),
           is_enable_alert_and_sms_tab: ''
            %>

<%= panel "Edit Project" do %>
  <%= render 'form', project_with_role: @project_with_role %>
<% end %>

app/views/projects/index.html.erb
<% content_for(:title) { "Projects"} %>
<% breadcrumb_buffer([{
    "Projects": nil
  }]) %>


<div class='header-wrapper clearfix'>
  <div class='pull-left'>
    <h3 class='header-title'> List of My Projects </h3>
    <%= render 'shared/search_form', url: projects_path %>
  </div>

  <div class='pull-right'>
    <%= link_new 'New Project', new_project_path() %>
  </div>
</div>

<div class="panel panel-info">
  <table class='table table-responsive'>
    <thead>
      <tr>
        <td width="250">Name</td>
        <td>Description</td>
        <td class='td-last'></td>
      </tr>
    </thead>
    <tbody>
      <% @my_projects.each do |project| %>
        <%= render 'project', project_with_role: ObjectWithRole.new(project), show_role: false %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate_for(@my_projects)%>


<% if @project_permissions.size > 0 %>
  <br />
  <br />
  <br />
  <h3 class='header-title'> Shared Projects </h3>
  <div class="panel panel-info">
    <table class='table table-responsive'>
      <thead>
        <tr>
          <td width="250">Name</td>
          <td>Description</td>
          <td class='td-last'></td>
        </tr>
      </thead>
      <tbody>
      <% @project_permissions.each do |permission| %>
        <%= render 'project', project_with_role: ObjectWithRole.new(permission.project, permission.role), show_role: true %>
      <% end %>
      </tbody>
    </table>
  </div>
  <%=paginate_for(@project_permissions, param_name: :shared_page) %>

<% end %>

app/views/projects/new.html.erb
<% content_for(:title) { "New Project"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      {"New Project": nil}]) %>


<%= render 'shared/project_alert',
           project_tab: 1,
           url_tab1: new_project_path,
           url_tab2: 'javascript:void(0)',
           url_tab3: 'javascript:void(0)',
           is_enable_alert_and_sms_tab: 'disabled'
            %>

<%= panel "New Project" do %>
<%= render 'form', project_with_role: @project_with_role %>
<% end %>

app/views/projects/share.html.erb
<% content_for(:title) { "Shared Project"} %>

<%= render 'shared/project_alert', 
           project_tab: 1,
           url_tab1: share_project_path(@project),
           url_tab2: share_project_alerts_path(@project),
           is_enable_alert_and_sms_tab: ''
            %>

<%=simple_form_for(@project, html: { class: 'form-inline form'}) do |f| %>

  <div class='input-row'>
    <%=f.input :name, input_html: {class: 'form-control', disabled: 'disabled'} %>
  </div>

  <%=f.input :description, as: :text, input_html: {class: 'form-control', disabled: 'disabled'}, wrapper_html: { class: 'inline'} %>

<% end %>

app/views/projects/sms_setting.html.erb
<% content_for(:title) { "SMS Settings"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      { "#{@project_with_role.object.name}": edit_project_path(@project_with_role.object)},
                      { "SMS Settings": nil}]) %>

<%= render 'shared/project_alert', 
           project_tab: 3,
           url_tab1: edit_project_path(@project_with_role.object),
           url_tab2: project_alerts_path(@project_with_role.object),
           url_tab3: sms_setting_project_path(@project_with_role.object),
           is_enable_alert_and_sms_tab: ''
            %>
<%= panel "SMS Settings" do %>
  <%=form_for(@project_with_role.object, url: update_sms_setting_project_path, method: 'POST', html: { class: 'form-inline form'}) do |f| %>
    <% input_attrs = @project_with_role.has_admin_role? ? {} : {disabled: 'disabled'} %>

    <div class="form-group horizontal-group">
      <label class="required"><abbr>*</abbr> SMS Channels</label>
      <div class="checkbox-list">
        <%= f.collection_check_boxes :channel_ids, @project_with_role.object.accessible_channels, :id, :name, include_hidden: false do |channel| %>
          <div>
          <%= channel.label do  %>
            <% if @project_with_role.object.is_active_channel? channel.object %>
              <%= channel.check_box({checked: true}.merge(input_attrs)) %>
            <% else %>
              <%= channel.check_box({checked: false}.merge(input_attrs)) %>
            <% end -%>
            
            <%= channel.text %>
          <% end -%>
          </div>
        <% end -%>
      </div>
    </div>

    <div class='form-group' id="sms-alert-time">
      <label class="control-label required"><abbr>*</abbr> SMS alert time</label>
      <div class="input-group">
        <span class="input-group-addon">From</span>
        <%= f.text_field :sms_alert_started_at, class: "form-control time start", autocomplete: :off, placeholder: 'hh:mm',disabled: input_attrs[:disabled] %>
      </div>
      
      <div class="input-group">
        <span class="input-group-addon">To</span>
        <%= f.text_field :sms_alert_ended_at, class: "form-control time end", autocomplete: :off, placeholder: 'hh:mm', disabled: input_attrs[:disabled] %>
      </div>
    </div>

    <div class='form-group'>
      <label class="control-label required"><abbr>*</abbr> SMS template</label>
      <%= f.text_area :sms_alert_template, as: :text, class: 'form-control', rows: 6, cols: 40, disabled: input_attrs[:disabled] %>
    </div>

    <div class='form-group'>
      <label></label>
      <%= sms_template_params_for(:project_sms_alert_template) %>
    </div>


    <% if @project_with_role.has_admin_role? %>
      <div class='form-group form-action-group'>
        <label></label>
        <%=f.submit 'Save', label: false, class: 'btn btn-primary btn-app' %>
      </div>
    <% end %>
  <% end %>  
<% end -%>         