config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  
  get 'sign_up' => 'registrations#new'

  post 'sign_up' => 'registrations#create'
  get 'confirm' => 'registrations#confirm'
  get 'welcome' => 'registrations#welcome'

  resources :group_messages

  resources :channel_accesses do
    collection do
      post 'national_gateway'
    end
  end

  resources :channels do
    member do
      put 'state'
    end
  end

  resources :passwords, only: [:new, :update] do
    collection do
      put 'request_change'
      put 'reset'
      get 'change'
    end
  end

  delete 'sign_out' => 'sessions#destroy'

  resources :permissions
  resources :project_permissions
  resources :channel_permissions

  resources :projects do
    member do
      get 'share'
      get 'sms_setting'
      post 'update_sms_setting'
    end

    collection do
      get 'list'
    end

    resources :alerts do

      collection do
        get 'matched'
        get 'share'
      end

      member do
        get 'new_groups'
        get 'new_keywords'
      end
      
    end
  end

  resources :alerts, only: [] do
    collection do
      get 'matched'
    end

    member do
      get 'new_groups'
      get 'new_keywords'
    end

    resources :alert_groups
    resources :alert_keywords

    resources :feed_entries do
      collection do
        get 'matched'
      end
    end
  end

  resources :groups do
    member do
      get 'new_members'
      get 'alerts'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
      get 'alerts'
    end
  end

  resources :users, only: [] do
    collection do
      get 'profile'
      put 'update_profile'

      get 'password'
      put 'update_password'
      get 'list'
    end

    member do
      put 'reset'
    end
  end

end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  url                  :string(255)
#  interval             :float(24)
#  interval_unit        :string(255)
#  email_template       :text(65535)
#  sms_template         :text(65535)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  alert_places_count   :integer          default(0)
#  alert_groups_count   :integer          default(0)
#  alert_keywords_count :integer          default(0)
#  from_time            :string(255)
#  to_time              :string(255)
#  project_id           :integer
#  channel_id           :integer
#

class Alert < ActiveRecord::Base
  include AlertMatchCriteria

  has_many :alert_groups, dependent: :destroy
  has_many :groups, through: :alert_groups

  has_many :alert_keywords, dependent: :destroy
  has_many :keywords, through: :alert_keywords

  has_many :alert_places, dependent: :destroy
  has_many :places, through: :alert_places

  has_many :feeds, dependent: :destroy
  has_many :feed_entries

  has_many :group_permissions, dependent: :nullify

  belongs_to :project
  belongs_to :channel

  # accepts_nested_attributes_for :alert_places, allow_destroy: true

  INTERVAL_UNIT_HOUR = "Hour"
  INTERVAL_UNIT_DAY  = "Day"

  INTERVAL_UNITS = [INTERVAL_UNIT_HOUR, INTERVAL_UNIT_DAY]

  validates :name, presence: true
  validates :url, presence: true
  validates :url, url: true

  attr_accessor :total_match

  def reset_error
    self.invalid_url = 0
    self.error_message = nil
  end

  def valid
    invalid_url < 3 && alert_keywords_count > 0
  end

  def self.valid
    where("invalid_url < ? AND alert_keywords_count > ?", ENV['MAX_ERROR_NUMBER'].to_i, 0)
  end

  def self.valid_url
    where("invalid_url < ? ", ENV['MAX_ERROR_NUMBER'].to_i)
  end

  def has_invalid_url_error
    self.invalid_url >= ENV['MAX_ERROR_NUMBER'].to_i
  end

  def self.apply_search
    Alert.includes(:keywords).where("alert_keywords_count > ?", 0).find_in_batches(batch_size: 5) do |alerts|
      AlertResult.new(alerts).run
    end
  end

  def apply_search
    AlertResult.new([self]).run
  end

  def in_minutes field
    field.split(":")[0].to_i * 60 + field.split(":")[1].to_i
  end

  def is_time_appropiate? sms_time
    working_minutes = sms_time.hour * 60 + sms_time.min
    in_minutes(self.from_time) <= working_minutes && working_minutes <= in_minutes(self.to_time)
  end

  def translate_message
    return "" unless self.project.sms_alert_template
    translate_options = {
      alert_name: self.name,
      total_match: self.total_match,
      keywords: self.keywords.map(&:name).join(", ")
    }

    StringSearch.instance.set_source(self.project.sms_alert_template).translate(translate_options)
  end

  def self.from_member(member_id)
    group_sql = Group.select('groups.id').joins('INNER JOIN memberships ON memberships.group_id = groups.id ')
                     .where([ 'memberships.member_id=?', member_id]).to_sql

    self.includes(:project).select('distinct alerts.id, alerts.*')
                           .joins('INNER JOIN alert_groups ON alert_groups.alert_id = alerts.id')
                           .where("alert_groups.group_id in (#{group_sql})")
  end

  def mark_error message
    self.invalid_url = self.invalid_url + 1
    self.error_message = message
    self.save(validate: false)
  end

  def self.migrate_channel
    Alert.transaction do
      Alert.find_each(batch_size: 100) do |alert|
        channel = alert.channel
        project = alert.project
        
        unless project.sms_alert_started_at && project.sms_alert_ended_at
          if alert.from_time && alert.to_time
            project.sms_alert_started_at = alert.from_time
            project.sms_alert_ended_at = alert.to_time
            project.sms_alert_template = alert.sms_template
            project.save!
          end
        end
        if channel
          channel_access = project.channel_accesses.select { |c| c.channel_id == channel.id }.first
          if !channel_access && channel
            project.channel_accesses.new(channel_id: channel.id, is_active: true)
            project.save!
          end
        end
      end
    end    
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :require_project_admin_role!, only: [:new, :create, :update, :destroy]
  before_action :check_channel_access!, only: [:create, :update]

  def new_groups
    alert = Alert.find(params[:id])
    existing_groups = alert.groups.ids

    groups = current_user.my_groups
    groups = groups.excludes(existing_groups) if existing_groups.length > 0
    groups = groups.from_query(params[:q]) if params[:q].present?
    render json: groups
  end

  def new_keywords
    alert = Alert.find(params[:id])
    existing_keywords = alert.keywords.ids

    keywords = Keyword.all
    keywords = keywords.excludes(existing_keywords) if existing_keywords.length > 0
    keywords = keywords.from_query(params[:q]) if params[:q].present?
    render json: keywords
  end

  def index
    @alerts = project_with_role.object.alerts
                                      .includes(:keywords, groups: :alert_groups)
                                      .order('updated_at DESC')
                                      .page(params[:page])
  end

  def new
    @alert = project_with_role.object.alerts.build
  end

  def create
    @alert = project_with_role.object.alerts.build(filter_params)

    if(@alert.save)
      redirect_to edit_project_alert_path(project_with_role.object, @alert), notice: 'Alert has been created'
    else
      flash.now[:alert] = 'Failed to create alert'
      render :new
    end
  end

  def edit
    @alert = project_with_role.object.alerts.includes(:groups, :keywords).find(params[:id])
  end

  def update
    @alert = project_with_role.object.alerts.find(params[:id])
    @alert.reset_error

    if(@alert.update_attributes(filter_params))
      redirect_to project_alerts_path(project_with_role.object), notice: 'Alert has been updated'
    else
      flash.now[:alert] = 'Could not save the alert'
      render :edit
    end
  end

  def destroy
    @alert = project_with_role.object.alerts.find(params[:id])
    if @alert.destroy
      redirect_to project_alerts_path(project_with_role.object), notice: 'Alert has been deleted'
    else
      redirect_to project_alerts_path(project_with_role.object), notice: 'Could not delete the alert'
    end
  end

  private
  def require_project_admin_role!
    project_with_role.has_admin_role!
  end

  def filter_params
    params.require(:alert).permit(:name, :url, :interval, :from_time, :to_time, :sms_template, :channel_id,
                                  alert_places_attributes: [:id, :place_id, :_destroy])
  end

  def check_channel_access!
    current_user.accessible_channel(params[:alert][:channel_id]) if params[:alert][:channel_id].present?
  end

  def project_with_role
    @project_with_role ||= current_user.accessible_project(params[:project_id])
  end

end

app/views/alerts/_alert_groups.html.erb
<div class="header-wrapper clearfix">
  <div class="pull-left"><h3 class='header-title'>Alert to Groups</h3></div>

  <div class="pull-right" >
    <% if project_with_role.has_admin_role? %>
      <div id='alert-group' >
        <div class="input-group search-wrapper">
          <input type="text" 
                class="form-control typeahead" placeholder="Group"
                id="alert-group-typeahead"
                data-url="<%= new_groups_alert_path(alert) %>" >

          <span class="input-group-btn">
            <%= link_to "Add Group", alert_alert_groups_path(alert), class: 'btn btn-primary btn-app typeahead-add', id: 'add-alert-group' %>
          </span>
        </div>

        <input type='hidden' id='alert-group-value' >
      </div>
    <% end %>
  </div>
</div>

<div id='alert-group-list'>
  <%= render 'alert_groups/groups', alert: alert, admin: project_with_role.has_admin_role? %>
</div>

app/views/alerts/_alert_keywords.html.erb
<div class="header-wrapper clearfix">
  <div class="pull-left"><h3 class='header-title'>Keywords to Search for</h3></div>

  <div class="pull-right">
    <% if project_with_role.has_admin_role? %>
      <div id='alert-keyword'>
        <div class="input-group search-wrapper">
          <input type="text" 
                class="form-control typeahead" placeholder="Keyword"
                id="alert-keyword-typeahead"
                data-url="<%= new_keywords_alert_path(alert) %>" >

          <span class="input-group-btn">
            <%= link_to "Add Keyword", alert_alert_keywords_path(alert), class: 'btn btn-primary btn-app typeahead-add', id: 'add-alert-keyword' %>
          </span>
        </div>

        <input type='hidden' id='alert-keyword-value' >
      </div>
    <% end %>
  </div>
</div>

<div id='alert-keyword-list'>
  <%= render 'alert_keywords/keywords', alert: alert, admin: project_with_role.has_admin_role? %>
</div>

app/views/alerts/_form.html.erb
<%= simple_form_for [project_with_role.object, alert], html: {class: 'form form-inline', id: 'form-alert'} do |f| %>
  <% disabled = project_with_role.has_admin_role? ? {} : {disabled: 'disabled'} %>
  <%=f.input :name, input_html: {class: 'form-control'}.merge(disabled) %>
  <%=f.input :url, input_html: {class: 'form-control'}.merge(disabled) %>

  <% if project_with_role.has_admin_role? %>
    <div class='form-group form-action-group'>
      <label></label>
      <%=f.submit 'Save', class: 'btn btn-primary btn-app', id: 'btn-alert-form' %>
    </div>
  <% end %>

<% end %>

app/views/alerts/edit.html.erb
<% content_for(:title) { "Edit Alert"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      { "#{@project_with_role.object.name}": edit_project_path(@project_with_role.object)},
                      {"Alerts": project_alerts_path(@project_with_role.object)},
                      {"#{@alert.name}": nil}]) %>

<%= render 'shared/project_alert',
            url_tab1: edit_project_path(@project_with_role.object),
            url_tab2: project_alerts_path(@project_with_role.object),
            url_tab3: sms_setting_project_path(@project_with_role.object),
            project_tab: 2,
            is_enable_alert_and_sms_tab: '' %>

<div class='form-wrapper'>
  <%= panel "Edit Alert" do %>
    <%= render 'form', project_with_role: @project_with_role, alert: @alert %>
  <% end %>

  <br />
  <%= render 'alert_groups', project_with_role: @project_with_role, alert: @alert %>

  <br />
  <br />

  <%= render 'alert_keywords', project_with_role: @project_with_role, alert: @alert %>
</div>

app/views/alerts/index.html.erb
<% content_for(:title) { "Alerts"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      { "#{@project_with_role.object.name}": edit_project_path(@project_with_role.object)},
                      { "Alerts": nil}]) %>


<%= render 'shared/project_alert',
            url_tab1: edit_project_path(@project_with_role.object),
            url_tab2: project_alerts_path(@project_with_role.object),
            url_tab3: sms_setting_project_path(@project_with_role.object),
            project_tab: 2,
            is_enable_alert_and_sms_tab: '' %>


<div class='header-wrapper clearfix' >
  <div class='pull-left'>
    <h3 class='header-title'> List of Alerts </h3>
  </div>

  <div class='pull-right'>
    <%# link_custom 'Alert Content', matched_project_alerts_path(@project_with_role.object), class: 'btn btn-default'%>
    <% if @project_with_role.has_admin_role? %>
      <span> </span>
      <%= link_new 'New Alert', new_project_alert_path(@project_with_role.object), 
                   class: 'btn btn-default',
                   style: 'margin-left: 5px;' %>
    <% end %>
  </div>
</div>


<div class="panel panel-info">
  <table class='table table-responsive'>
    <thead>
      <tr>
        <td width='400' >Alert</td>
        <td>Groups</td>
        <td>Keywords</td>
        <% if @project_with_role.has_admin_role? %>
          <td class='td-last'>Action</td>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @alerts.each do |alert| %>
        <tr>
          <td>
            <%= link_to alert.name, edit_project_alert_path(@project_with_role.object, alert) %>
            <div><%= alert.url %></div>
            <% if alert.channel %>
            <p class="sub-text">
              <span>Sms alert </span> <%= alert_time(alert) %>
                using channel <b><%= build_channel_list alert.project.channels %></b>
            </p>
            <% end %>
            <% if alert.error_message %>
              <span class='error'>
               <i class='glyphicon glyphicon-remove'> </i> <%= alert.error_message%>
              </span>
            <% end %>
          </td>
          <td><%= truncate(alert.groups.map(&:name).join(", "), length: 120) %></td>
          <td><%= truncate(alert.keywords.map(&:name).join(", "), length: 120) %></td>
          <% if @project_with_role.has_admin_role? %>
          <td>
             <%= link_edit " ", edit_project_alert_path(@project_with_role.object, alert) %>
             <%= link_destroy " ", project_alert_path(@project_with_role.object, alert),
                              method: :delete,
                              data: { confirm: 'Are you sure to delete this alert ?'} %>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate_for(@alerts) %>

app/views/alerts/matched.html.erb
<%= page_title "Alert matched" %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      { "#{@project_with_role.object.name}": edit_project_path(@project_with_role.object)},
                      {"Alerts": project_alerts_path(@project_with_role.object)},
                      {"Matched alerts": nil}]) %>

<%= render 'shared/project_alert',
            url_tab1: edit_project_path(@project_with_role.object),
            url_tab2: project_alerts_path(@project_with_role.object),
            project_tab: 2,
            is_enable_alert_and_sms_tab: '' %>


<h3> Alerts that matched criteria for </h3>
<p class="color:gray; font-size: 90%;"><%= @date_range.from %>, <%= @date_range.to %></p>
<% @alerts.each do |alert| %>
  <div style='padding-top: 15px; margin-bottom: 10px;'>
    <h3>
      <%=link_to alert.name, matched_alert_feed_entries_path(alert.id, from: @date_range.from, to: @date_range.to) %>
      <span class='badge badge-danger'> <%= alert.total_match %> </span>
    </h3>

    <p style='color:gray; font-size: 90%; font-style:italic;'>
      <%= alert.keywords.pluck(:name).join(", ")%>
    </p>
    <%= alert.url%>

  </div>
<% end %>

app/views/alerts/new.html.erb
<% content_for(:title) { "Create Alert"} %>
<% breadcrumb_buffer([{ "Projects": projects_path},
                      { "#{@project_with_role.object.name}": edit_project_path(@project_with_role.object)},
                      {"Alerts": project_alerts_path(@project_with_role.object)},
                      {"New Alert": nil}]) %>

<%= render 'shared/project_alert',
            url_tab1: edit_project_path(@project_with_role.object),
            url_tab2: project_alerts_path(@project_with_role.object),
            url_tab3: sms_setting_project_path(@project_with_role.object),
            project_tab: 2,
            is_enable_alert_and_sms_tab: '' %>



<%= panel "New Alert" do %>
  <%= render'form', project_with_role: @project_with_role, alert: @alert %>
<% end %>